//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Event.java
//  @ Date : 6/26/2015
//  @ Author : 
//
//




public class Event {
	public Object id;
	public Object name;
	public Object evenStartTime;
	public Object duration;
	public Object votingWindowStartTime;
	public Object votingWindowEndTime;
	public Object enrolledUsers;
	public Object candidates;
	public Object status;
}
