DROP  SCHEMA IF EXISTS followyourstar;
CREATE SCHEMA IF NOT EXISTS followyourstar;
USE followyourstar;

CREATE TABLE IF NOT EXISTS LOCATION (
   ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(50) NOT NULL,
   CITY VARCHAR(10) NOT NULL,
   START_TIME DATE NOT NULL,
   STATE VARCHAR(10),
   PRIMARY KEY (ID)

);
CREATE TABLE IF NOT EXISTS EVENT (
   ID INT NOT NULL AUTO_INCREMENT,
   LOCATION_FK INT,
   DURATION DECIMAL(4) NOT NULL,
   LAST_UPDATE DATE,
   TZ_OFFSET DECIMAL(4),
   VOTING_STARTS DATE NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   START_TIME DATE NOT NULL,
   STATE VARCHAR(10),
   PRIMARY KEY  (ID),
   FOREIGN KEY (LOCATION_FK) REFERENCES LOCATION(ID)
);

CREATE TABLE IF NOT EXISTS BROADCAST (
   LOCATION_PK INT NOT NULL,
   CALLSIGN VARCHAR(10) NOT NULL,
   NETWORK VARCHAR(10) NOT NULL,
   PRIMARY KEY (LOCATION_PK),
   FOREIGN KEY (LOCATION_PK) REFERENCES LOCATION(ID)
);

CREATE TABLE IF NOT EXISTS ADDRESS (
   LOCATION_PK INT NOT NULL,
   ZIPCODE VARCHAR(10) NOT NULL,
   ADDRESS VARCHAR(50) NOT NULL,
   PRIMARY KEY (LOCATION_PK),
   FOREIGN KEY (LOCATION_PK) REFERENCES LOCATION(ID)
);


CREATE TABLE IF NOT EXISTS CONTESTANT (
   ID INT NOT NULL AUTO_INCREMENT,
   EVENT_FK INT NOT NULL,
   NAME VARCHAR(10) NOT NULL,
   DECRIPTION VARCHAR(50) NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (EVENT_FK) REFERENCES EVENT(ID)
);

CREATE TABLE IF NOT EXISTS USER (
   ID INT NOT NULL AUTO_INCREMENT,
   EMAIL VARCHAR(20) NOT NULL,
   FIRST_NAME VARCHAR(10) NOT NULL,
   LAST_NAME VARCHAR(50) NOT NULL,
   USER_PASSWORD VARCHAR(10) NOT NULL,
   PORTRAIT VARCHAR(50),
   ROLE VARCHAR(10),
   PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS VOTER (
   ID INT NOT NULL AUTO_INCREMENT,
   EVENT_FK INT NOT NULL,
   CONTESTANT_FK INT NOT NULL,
   USER_FK INT NOT NULL,
   ENROLLMENT_TIME DATE NOT NULL,
   VOTED_ON DATE NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (EVENT_FK) REFERENCES EVENT(ID),
   FOREIGN KEY (CONTESTANT_FK) REFERENCES CONTESTANT(ID),
   FOREIGN KEY (USER_FK) REFERENCES USER(ID)
);

INSERT INTO USER(FIRST_NAME, LAST_NAME,EMAIL, USER_PASSWORD, ROLE) values ('root','root','root@followyourstar.com','root','admin');

show tables;


